//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTSPDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cse_summary_sixmonths
    {
        public int response_id { get; set; }
        public Nullable<System.DateTime> date_first { get; set; }
        public Nullable<System.DateTime> date_last { get; set; }
        public Nullable<System.DateTime> show_date { get; set; }
        public string rock_star_winners { get; set; }
        public string super_stars_winner { get; set; }
        public Nullable<double> super_stars_winner_ave { get; set; }
        public string super_stars_runnerup { get; set; }
        public Nullable<double> super_stars_runnerup_ave { get; set; }
        public string supporting_cast_winner { get; set; }
        public Nullable<double> supporting_cast_winner_stars { get; set; }
        public string supporting_cast_runnerup { get; set; }
        public Nullable<double> supporting_cast_runnerup_stars { get; set; }
    }
}
