//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTSPDF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class new_DbEntities : DbContext
    {
        public new_DbEntities()
            : base("name=new_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cse_summary_sixmonths> cse_summary_sixmonths { get; set; }
        public virtual DbSet<cse_summary_sixmonths_test> cse_summary_sixmonths_test { get; set; }
    }
}
